version: "2"
linters:
  enable:
    - gocritic
    - godot
    - misspell
    - nolintlint
    - predeclared
    - revive
    - staticcheck
    - unconvert
    - wastedassign
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
          - staticcheck
        path: .*test.*.go$
        text: should not use dot imports
      - linters:
          - revive
        path: (pkg/common|pkg/agent/aggregation/types)
        text: "var-naming: avoid meaningless package names"
    paths:
      - zz_generated.*
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/gardener/network-problem-detector
  exclusions:
    generated: lax
    paths:
      - zz_generated.*
      - third_party$
      - builtin$
      - examples$
